apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: task-pv-storage
              persistentVolumeClaim:
                claimName: jhub/claim-dj-40monumetric-2ecom
          containers:
          - name: hello
            image: busybox
            volumeMounts:
             - mountPath: "/sync"
               name: task-pv-storage
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
